<?php
 $denglu_data = array (
  0 => 
  array (
    'apiKey' => 'www.denglu.cc',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_1.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_1.gif',
    'shareFlag' => '1',
    'mediaName' => 'Google',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_1.png',
    'mediaNameEn' => 'google',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_1.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_1.png',
    'mediaID' => '1',
  ),
  1 => 
  array (
    'apiKey' => 'OIoFF22kx6AH8FFtmREsuRr5',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_19.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_19.gif',
    'shareFlag' => '1',
    'mediaName' => '百度',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_19.png',
    'mediaNameEn' => 'baidu',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_19.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_19.png',
    'mediaID' => '19',
  ),
  2 => 
  array (
    'apiKey' => '2088502992232835',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_18.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_18.gif',
    'shareFlag' => '1',
    'mediaName' => '支付宝',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_18.png',
    'mediaNameEn' => 'alipayquick',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_18.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_18.png',
    'mediaID' => '18',
  ),
  3 => 
  array (
    'apiKey' => '3a03422b4ae92c32ebd74905e6713aa104e321f46',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_17.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_17.gif',
    'shareFlag' => '0',
    'mediaName' => '天涯',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_17.png',
    'mediaNameEn' => 'tianya',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_17.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_17.png',
    'mediaID' => '17',
  ),
  4 => 
  array (
    'apiKey' => '12447137',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_16.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_16.gif',
    'shareFlag' => '1',
    'mediaName' => '淘宝',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_16.png',
    'mediaNameEn' => 'taobao',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_16.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_16.png',
    'mediaID' => '16',
  ),
  5 => 
  array (
    'apiKey' => '100232596',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_13.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_13.gif',
    'shareFlag' => '0',
    'mediaName' => 'QQ空间',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_13.png',
    'mediaNameEn' => 'qzone',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_13.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_13.png',
    'mediaID' => '13',
  ),
  6 => 
  array (
    'apiKey' => 'dj0yJmk9OGFGbEFLR0UzTmNEJmQ9WVdrOWNVdHZNMkl3TkdzbWNHbzlORFU1TkRZek1qWXkmcz1jb25zdW1lcnNlY3JldCZ4PTA2',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_12.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_12.gif',
    'shareFlag' => '1',
    'mediaName' => '雅虎',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_12.png',
    'mediaNameEn' => 'yahoo',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_12.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_12.png',
    'mediaID' => '12',
  ),
  7 => 
  array (
    'apiKey' => '0ae0a7fdee8d7e4220a1f7f9cba87ac6',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_9.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_9.gif',
    'shareFlag' => '1',
    'mediaName' => '豆瓣网',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_9.png',
    'mediaNameEn' => 'douban',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_9.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_9.png',
    'mediaID' => '9',
  ),
  8 => 
  array (
    'apiKey' => '353467810615ed87d110573bec4dcdf2',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_8.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_8.gif',
    'shareFlag' => '1',
    'mediaName' => '开心网',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_8.png',
    'mediaNameEn' => 'kaixin001',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_8.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_8.png',
    'mediaID' => '8',
  ),
  9 => 
  array (
    'apiKey' => '4aca218f3cba4d2bb35253c3e552fa81',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_7.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_7.gif',
    'shareFlag' => '0',
    'mediaName' => '人人网',
    'sortIndex' => '0',
    'inviteFlag' => '0',
    'commentReplyFlag' => '0',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_7.png',
    'mediaNameEn' => 'renren',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_7.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_7.png',
    'mediaID' => '7',
  ),
  10 => 
  array (
    'apiKey' => '2KRXJp1IPa4axdHQ',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_6.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_6.gif',
    'shareFlag' => '0',
    'mediaName' => '网易微博',
    'sortIndex' => '0',
    'inviteFlag' => '0',
    'commentReplyFlag' => '0',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_6.png',
    'mediaNameEn' => 'netease',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_6.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_6.png',
    'mediaID' => '6',
  ),
  11 => 
  array (
    'apiKey' => 'GxdGKzJYnP7eu7e85fs9',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_5.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_5.gif',
    'shareFlag' => '0',
    'mediaName' => '搜狐微博',
    'sortIndex' => '0',
    'inviteFlag' => '0',
    'commentReplyFlag' => '0',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_5.png',
    'mediaNameEn' => 'sohu',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_5.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_5.png',
    'mediaID' => '5',
  ),
  12 => 
  array (
    'apiKey' => 'c3c2171b11fc419dbe2832dffdf697d1',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_4.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_4.gif',
    'shareFlag' => '0',
    'mediaName' => '腾讯微博',
    'sortIndex' => '0',
    'inviteFlag' => '0',
    'commentReplyFlag' => '0',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_4.png',
    'mediaNameEn' => 'tencent',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_4.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_4.png',
    'mediaID' => '4',
  ),
  13 => 
  array (
    'apiKey' => '561723186',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_3.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_3.gif',
    'shareFlag' => '0',
    'mediaName' => '新浪微博',
    'sortIndex' => '0',
    'inviteFlag' => '0',
    'commentReplyFlag' => '0',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_3.png',
    'mediaNameEn' => 'sina',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_3.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_3.png',
    'mediaID' => '3',
  ),
  14 => 
  array (
    'apiKey' => '0000000044072822',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_2.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_2.gif',
    'shareFlag' => '0',
    'mediaName' => 'MSN',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_2.png',
    'mediaNameEn' => 'windowslive',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_2.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_2.png',
    'mediaID' => '2',
  ),
  15 => 
  array (
    'apiKey' => '4728201597',
    'mediaIconImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_21.gif',
    'mediaIconNoImageGif' => 'http://open.denglu.cc/images/denglu_second_icon_no_21.gif',
    'shareFlag' => '1',
    'mediaName' => '网易163',
    'sortIndex' => '0',
    'inviteFlag' => '1',
    'commentReplyFlag' => '1',
    'mediaImage' => 'http://open.denglu.cc/images/denglu_second_21.png',
    'mediaNameEn' => 'netease163',
    'mediaIconNoImage' => 'http://open.denglu.cc/images/denglu_second_icon_no_21.png',
    'mediaIconImage' => 'http://open.denglu.cc/images/denglu_second_icon_21.png',
    'mediaID' => '21',
  ),
)

?>